// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4yrif5LbVTgFO8hdMnAfC9DBCkRVR2R0',
    appId: '1:70450704587:web:1cfe038c37644f9047ab4e',
    messagingSenderId: '70450704587',
    projectId: 'ml-venomous-snakes',
    authDomain: 'ml-venomous-snakes.firebaseapp.com',
    databaseURL: 'https://ml-venomous-snakes-default-rtdb.firebaseio.com',
    storageBucket: 'ml-venomous-snakes.appspot.com',
    measurementId: 'G-NKM66EJ98E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbyeN5sajQvsCKX6MDAhjCfHUfCyllGXw',
    appId: '1:70450704587:android:2277570c6521a05247ab4e',
    messagingSenderId: '70450704587',
    projectId: 'ml-venomous-snakes',
    databaseURL: 'https://ml-venomous-snakes-default-rtdb.firebaseio.com',
    storageBucket: 'ml-venomous-snakes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATX3eKcWxy6KLNxODNBZTp_WeyXdaj8Is',
    appId: '1:70450704587:ios:aecfbb7f8a49006247ab4e',
    messagingSenderId: '70450704587',
    projectId: 'ml-venomous-snakes',
    databaseURL: 'https://ml-venomous-snakes-default-rtdb.firebaseio.com',
    storageBucket: 'ml-venomous-snakes.appspot.com',
    iosClientId: '70450704587-p4sv5rgg9mo9smfbs85a8nkhtip079d1.apps.googleusercontent.com',
    iosBundleId: 'com.example.snakeIdentificationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATX3eKcWxy6KLNxODNBZTp_WeyXdaj8Is',
    appId: '1:70450704587:ios:aecfbb7f8a49006247ab4e',
    messagingSenderId: '70450704587',
    projectId: 'ml-venomous-snakes',
    databaseURL: 'https://ml-venomous-snakes-default-rtdb.firebaseio.com',
    storageBucket: 'ml-venomous-snakes.appspot.com',
    iosClientId: '70450704587-p4sv5rgg9mo9smfbs85a8nkhtip079d1.apps.googleusercontent.com',
    iosBundleId: 'com.example.snakeIdentificationApp',
  );
}
